### ISSUE TITLE
我使用的是Azure香港网站服务，php环境是iis，没跑apache

### ISSUE THREAD

**Issue by vochina** [wzxjohn/moeSS#12]
如题，打开提示The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.找不到文件，估计是重定向的问题，看来htaccess是没办法用了，我这种php跑iis的情况怎么破，ps：我是小白。

**Comment by wzxjohn** [comment]
与项目无关的问题请不要开 issue ，谢谢配合！
