### ISSUE TITLE
Readme.md关于升级状态描述不明晰

### ISSUE THREAD

**Issue by cdiscrete** [wzxjohn/moeSS#14]
没有说清楚sql升级patch是否是各版本通用的。
比如说我现在的情况是
```
commit 684dc4b2f4e2e557f5b005feac8b9f27c91eb512
Merge: d9fa5f0 6fe2ac6
```
我就不知道update用的sql是否可用。

建议使用commit的id来命名升级用的sql，比如从[旧commit id][新id].sql

**Comment by wzxjohn** [comment]
这个数据库的升级还在考虑如何发布，确实很麻烦。最好的方法还是自己对比一下文件和数据库的区别。

**Comment by cdiscrete** [comment]
对，目前我是逐个版本对比的。然而现在commit差了几个了，逐一对比还是很累的。

我的建议是，使用增量的方式发布数据库更新。每次有sql的commit都发布一次sql更新，这样即使是很老的版本也可以写脚本批量导入sql。

**Comment by wzxjohn** [comment]
我这次添加了 update 文件夹的原因就是准备开始发布增量更新。你只需要关注一下 ShadowSocks.sql 文件的修改就可以了。
