### ISSUE TITLE
config-sample.php文件笔误

### ISSUE THREAD

**Issue by JAM2199562** [wzxjohn/moeSS#23]
在创建数据库语句里面是moess_sessions
CREATE TABLE IF NOT EXISTS `moess_sessions` (
        `id` varchar(40) NOT NULL,
        `ip_address` varchar(45) NOT NULL,
        `timestamp` int(10) unsigned DEFAULT 0 NOT NULL,
        `data` blob DEFAULT '' NOT NULL,
        PRIMARY KEY (id),
        KEY `ci_sessions_timestamp` (`timestamp`)
);
但是config-sample.php文件中写的是
$config['sess_save_path']                = 'moess_session';

**Comment by wzxjohn** [comment]
确实是笔误，马上修正。

**Comment by wzxjohn** [comment]
Fixed after d67feb4aba33633b88a9f574f244e043c2483593
