### ISSUE TITLE
管理套餐和购买流量界面都打不开

### ISSUE THREAD

**Issue by JAM2199562** [wzxjohn/moeSS#26]
首先解释一下，本人不懂代码，github也不太会用，小白之处还望体谅，你这个项目蛮好的，我拿来做前端跟几个朋友分享，感谢您的劳动。
sql已经正常导入了，也能看见goods的表了，下面是问题的描述。
管理界面：admin/goods.html
报错：The page you requested was not found.
购买界面：user/view_goods.html
报错：
Fatal error: Call to undefined method User_model::get_goods() in /webroot/application/controllers/User.php on line 902

A PHP Error was encountered

Severity: Error

Message: Call to undefined method User_model::get_goods()

Filename: controllers/User.php

Line Number: 902

Backtrace:

然后我简单做了个grep，大概是这个样子的
 grep -ri get_goods ./*
./application/controllers/User.php:            $data['goods'] = $this->user_model->get_goods();
不懂代码，但是感觉这个get_goods就出现了一次怎么都不对吧？

**Comment by JAM2199562** [comment]
然后发现还有一些bug貌似
/user.html

non-object

Filename: controllers/User.php

Line Number: 81

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 81
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 81

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 81
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 82

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 82
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 94

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 94
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 95

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 95
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 96

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 96
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 97

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 97
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 98

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 98
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 99

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 99
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 


A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 100

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 100
 Function: _error_handler 

File: /var/www/html/index.php
 Line: 292
 Function: require_once 

还有
/user/my_info.html
non-object

Filename: controllers/User.php

Line Number: 346

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 346
 Function: _error_handler 
encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 347

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 347
encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: controllers/User.php

Line Number: 348

Backtrace:

File: /var/www/html/application/controllers/User.php
 Line: 348

**Comment by wzxjohn** [comment]
请仔细查看中文说明。
[中文说明](https://www.evernote.com/shard/s42/sh/7a30525d-a949-4132-9916-1f4fbdbf4828/6eca7d1ce520e173b1a5ebf9489a766d)
开源版本没有支付功能，任何支付有关的问题请不要提交 Issue.

**Comment by wzxjohn** [comment]
不过 /user.html 不应该出错，我测试过了开源版 /user.html 也不应该出现任何问题的。

**Comment by JAM2199562** [comment]
支付功能我也用不到，这个无所谓，不过以后完美一点的话，把这个报错页面隐藏了或者在页面上显示为不可用应该会比现在好一点。
那个/user.html 咋说呢，页面最上面多了一堆报错，但是拉到最下面，还真是都完整显示了，也许这个也跟支付功能有关？

**Comment by JAM2199562** [comment]
不管它了，还是很感谢，我把代码回滚回去用着好了

**Comment by wzxjohn** [comment]
支付功能不用的话直接在 application/views/user/user_sidebar.php 中删除 77-81 即可。
你的这个 User 绝对是出了问题，不要回滚代码。你看看是不是没导入 sql 文件？还是你的文件没有覆盖全？把你 User.php 81 行左右贴出来看一下吧。

**Comment by JAM2199562** [comment]
代码我确实没改过的，除了首页一句话，别的都没动过，不过我已经降级了，现在一切都好，就不折腾了，多谢。
