### ISSUE TITLE
Message: touch(): Unable to create file 

### ISSUE THREAD

**Issue by cdiscrete** [wzxjohn/moeSS#32]
A PHP Error was encountered

Severity: Warning

Message: touch(): Unable to create file moess_session/asiass_session{this is an example} because No such file or directory

Filename: drivers/Session_files_driver.php

Line Number: 228

Backtrace:

---

在绝大多数管理后台和用户登录、后台出现。
已将session目录权限设为777

**Comment by wzxjohn** [comment]
更新的时候注意看修改配置文件的要求。

**Comment by cdiscrete** [comment]
那么你的说明可能漏了一个s，是sessions而不是session。或者你的表名是错的。

**Comment by wzxjohn** [comment]
。。。如果是配置文件少 s 出错不会报你这个错误。不过这个说明确实有问题。我之前修正了，不过似乎在某次 merge 的时候被回滚了。
