### ISSUE TITLE
后台无法修改管理员密码，无法修改默认加密方式，无法更改邮件template

### ISSUE THREAD

**Issue by cdiscrete** [wzxjohn/moeSS#4]
我还是自己去phpmyadmin手动改的ˊ_>ˋ

可以考虑加上ss-panel的每月充值流量的cron功能。
另外，如果有更新可以直接pull么？数据库会不会因pull之后无法使用？

**Comment by wzxjohn** [comment]
你说的这几个我都已经考虑到了，并且已经实现了大部分。数据库不会无法使用，但是因为更新修改了数据库结构，所以程序本身会出现问题。所以如果更新安装的话建议保留user表，其余的表全部删除重建。等你这次说的这些功能我都实现了之后应该就会进入一个比较稳定的版本，那之后就不会轻易修改数据库了。

**Comment by wzxjohn** [comment]
Fixed after 14c8528a8407c01db128781012f37ae1fb27097f
