### ISSUE TITLE
除了母鸡外的后端均不能正确打开端口

### ISSUE THREAD

**Issue by rootliang** [wzxjohn/moeSS#40]
Python server.py能够提示db. 但是查看开放端口则没有，是哪里设置不当吗

**Comment by wzxjohn** [comment]
请检查你的后端的各种设置。出现这个情况与前端完全无关。

**Comment by rootliang** [comment]
后端能正常启动但打不开端口，居然还提示端口了就是没打开端口，该怎么配置
