### ISSUE TITLE
一个moeSS如何管理多台VPS上的shadowsocks manyuser

### ISSUE THREAD

**Issue by gaojifans** [wzxjohn/moeSS#41]
VPS A 搭建了moeSS + shadowsocks manyuser
VPS B 只搭建了shadowsocks manyuser ，数据库配置的是用VPS A的
现在想通过把VPS B上shadowsocks manyuser接入到VPS A上的 moeSS面板进行管理
VPS A的Config.py 中的配置：
#Config
MYSQL_HOST = 'localhost'
MYSQL_PORT = 3306
MYSQL_USER = 'shadowsocks'
MYSQL_PASS = 'password'
MYSQL_DB = 'shadowsocks'

MANAGE_PASS = '123456'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '107.170.250.196'
#make sure this port is idle
MANAGE_PORT = 23333

VPS B的Config.py 中的配置：（VPS A IP=107.170.250.196）
#Config
MYSQL_HOST = '107.170.250.196'
MYSQL_PORT = 3306
MYSQL_USER = 'shadowsocks'
MYSQL_PASS = 'password'
MYSQL_DB = 'shadowsocks'

MANAGE_PASS = '123456'
#if you want manage in other server you should set this value to global ip
MANAGE_BIND_IP = '107.170.250.196'
#make sure this port is idle
MANAGE_PORT = 23333

python server.py启动 VPS B 上的出现以下错误：

INFO: loading config from config.json
shadowsocks 2.6.8
2015-02-27 16:02:00 ERROR    [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/home/shadowsocks/shadowsocks/server_pool.py", line 64, in _loop
    mgr.add_to_loop(loop)
  File "/home/shadowsocks/shadowsocks/asyncmgr.py", line 49, in add_to_loop
    self._sock.bind((Config.MANAGE_BIND_IP, Config.MANAGE_PORT))
  File "<string>", line 1, in bind
error: [Errno 99] Cannot assign requested address
Unhandled exception in thread started by <function _loop at 0xb72d6bfc>
Traceback (most recent call last):
  File "/home/shadowsocks/shadowsocks/server_pool.py", line 71, in _loop
    os.exit(0)
AttributeError: 'module' object has no attribute 'exit'

求问，该如何解决

**Comment by wzxjohn** [comment]
配置问题，特别是与项目无关的配置问题请不要发 issue。已邮件回答。

**Comment by Zachary-Leung** [comment]
同求解决方法

**Comment by devillaws** [comment]
这里也能求一份解决方案吗^ ^,devillawsx@gmail.com
