### ISSUE TITLE
关于流量重置的问题

### ISSUE THREAD

**Issue by LiuJason-CN** [wzxjohn/moeSS#44]
不知道是我设置的问题还是作者您特意的，我这里用户每月的流量是没有清除的。。。是需要自行设置吗？还是我的部署有问题？

我现在每月流量重置我是通过在mysql中设定event实现的：
CREATE EVENT monthly_reset
ON SCHEDULE EVERY 1 MONTH
STARTS '2015-05-01 00:01:00' 
DO UPDATE user SET u = '0', t = ‘0’ WHERE plan = '3G' OR plan = '5G' OR plan = '10G'

**Comment by Ehekatl** [comment]
php是动态语言 你不主动运行是不会起作用的

**Comment by LiuJason-CN** [comment]
请问是否需要建立cron规则访问某个php才能重置流量呢？那个php的路径在哪里呀？感谢作者orz

**Comment by wzxjohn** [comment]
目前系统里没有设计这个模块，之前有想加入这个模块，但是考虑我这套系统是给流量收费制的提供商使用的，所以就没有加入。另外，每天的签到可以获得大量的流量，所以其实可以通过增大签到可获得的流量来实现这个功能，同时还能统计总流量，而不是每月清空一次总流量。

**Comment by LiuJason-CN** [comment]
哦哦，我倒是在mysql中设置了event实现了，不过始终不清空的话貌似用户看自己的套餐用量不是很方便呢。还有就是用户管理的分页问题。。。其实分页做起来也不是很麻烦吧，用户多了的话会比较卡（现在600多），虽然我现在都是直接在数据库里修改。。
