### ISSUE TITLE
登录和注册页面不跳转

### ISSUE THREAD

**Issue by jiachenwang** [wzxjohn/moeSS#48]
按照教程：https://www.evernote.com/shard/s42/sh/7a30525d-a949-4132-9916-1f4fbdbf4828/6eca7d1ce520e173b1a5ebf9489a766d ，配置完成（邮件收发跳过了）。

用户和管理界面登录不跳转，卡在“正在登陆，请稍候。。。”
后台注入邀请码后，注册界面不跳转

**Comment by iOrange92** [comment]
这个问题之前有人遇到过，你看看是不是你的 Apache 返回的状态码是 404 而不是正常的 200。请求登录的时候如果得到了 404
的返回会出这个不跳转的问题。这个我还在考虑要怎么完善一下。

**Comment by jiachenwang** [comment]
我看了一下，确实返回的是404……

系统是debian7 x64。DO做了snapshot，需要的话，可以传给你一下

**Comment by jiachenwang** [comment]
@wzxjohn 
第一次是用DO的LAMP建的droplet，登陆界面不跳转。第二次自己在裸的debian7 x64上手工apt-get的amp，也出现同样的问题……

“其实这好像并不是我程序的 Bug 而是 Apache 安装时候设置问题导致的 Bug 。。。因为在我自己的 Apache 环境里完全没有问题，不过很多用 LAMP 之类的一键包安装的就会出现这个问题。”

**Comment by wzxjohn** [comment]
@2130qwer 手动 apt-get amp 是什么鬼。。。

**Comment by jiachenwang** [comment]
amp: apache2, mysql-server, php5 etc

**Comment by wzxjohn** [comment]
@2130qwer 如果方便的话能邮件联系我把你装好的机器的管理信息发给我么？我看看能不能查出来是什么问题，如果是程序的问题的话那刚好修一下 Bug。

**Comment by jiachenwang** [comment]
好的。不过，没找到你邮件地址啊

可否把邮箱地址发邮件给我？

**Comment by wzxjohn** [comment]
@2130qwer 已经发邮件给你了，不过还没收到你的回复=。=

**Comment by wzxjohn** [comment]
@2130qwer 的 404 的问题已经解决，经排查发现是 Apache 的 rewrite 模块并没有开启导致了。由于我的程序设置了如果检测不到 rewrite 模块就自动把请求转交给 index.php ，所以虽然 apache 的返回码是 404，缺并不太影响使用。只是 JS 在请求数据的时候，因为返回码是 404，导致程序卡死了。
