### ISSUE TITLE
作者在中文配置中的Nginx这一块需要提醒下配置下nginx的pathinfo支持

### ISSUE THREAD

**Issue by soulrenger** [wzxjohn/moeSS#49]
Nginx配置教程不完整，遇到404情况后发现是nginx下的 pathinfo支持没有配置，希望作者重新编辑下中文wiki，解决方法在https://www.v2ex.com/t/213561#reply7的第七楼，和repo主的稍微有点不一样，仅供参考

**Comment by wzxjohn** [comment]
已修改，感谢提供教程！
