### ISSUE TITLE
如何修改管理员密码

### ISSUE THREAD

**Issue by qianchenzhumeng** [wzxjohn/moeSS#52]
管理员默认密码admin，如果要修改，需要输入原密码，但是输入原密码后，会提示“Please enter at least 6 characters.”。那该如何修改管理员密码呢？

**Comment by wzxjohn** [comment]
管理员默认密码是 admin/admin12345 ，并不是 admin 哦

**Comment by qianchenzhumeng** [comment]
你自己去试！

**Comment by qianchenzhumeng** [comment]
哦，从这篇博客（https://blog.linuxeye.com/426.html）里面给的地址（git clone https://github.com/monoking/moeSS.git）克隆来的版本，管理员默认密码是admin，尽管博客里面说是admin12345，但是并不是。已经手工修改数据库解决了。
