### ISSUE TITLE
SS server的连接如何配置呢？

### ISSUE THREAD

**Issue by supermariogo** [wzxjohn/moeSS#54]
能成功的运转moeSS了。
但是不明白moeSS如何控制ss server？

比如新用户注册了，得到了ss server的地址和端口号，moeSS是怎么更新ss server的配置呢？

**Comment by wzxjohn** [comment]
moeSS 通过直接修改 ss manyuser 的 DB 达到通信的目的，因为 ss manyuser 会从 DB 读取用户名密码及端口的配置，所以只需要通过共用 DB 即可做到相互通信。
